site_name: Sistema de Agendamento - Politécnico UFSM
site_description: Documentação do sistema de agendamento de salas do Colégio Politécnico da UFSM
site_author: Equipe de Desenvolvimento
theme:
  name: material
  language: pt
  palette:
    # Tema claro
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Modo escuro
    # Tema escuro
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  font:
    text: "Roboto"
    code: "Fira Code"
  logo: assets/logo-ufsm.png
  favicon: assets/favicon.png
  features:
    - navigation.expand
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Início: index.md
  - Tutorial: tutorial.md
  - Requisitos: requisitos.md
  - Sobre: sobre.md

markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - nl2br
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - styles/custom.css

extra_javascript:
  - scripts/custom.js
